sudo: false

services:
  - memcached
  - docker

language: php
php:
- 7.2

addons:
  hosts:
    - web-resource-cache-mysql-host
    - memcached

env:
  global:
    - APP_ENV=test
    - APP_SECRET=Secret!
    - DATABASE_URL=mysql://web_resource_cache_db_user:secret@web-resource-cache-mysql-host:33066/web_resource_cache_db_name
    - WEB_RESOURCE_CACHE_MYSQL_ROOT_PASSWORD=root
    - WEB_RESOURCE_CACHE_DATABASE_NAME=web_resource_cache_db_name
    - WEB_RESOURCE_CACHE_DATABASE_USER=web_resource_cache_db_user
    - WEB_RESOURCE_CACHE_DATABASE_PASSWORD=secret
    - WEB_RESOURCE_CACHE_DATABASE_DATA_PATH=./var/docker-mysql/web-resource-cache-db
    - WEB_RESOURCE_CACHE_RABBITMQ_USER=rabbit
    - WEB_RESOURCE_CACHE_RABBITMQ_PASS=rabbit

cache:
  directories:
  - $HOME/.composer/cache/files

before_install:
  - mkdir -p $WEB_RESOURCE_CACHE_DATABASE_DATA_PATH
  - mkdir -p var/log/nginx
  - mkdir -p var/log/supervisor
  - chmod -R 0777 var/log

install:
  - cd docker && ./init.sh && cd ..

before_script:
  - phpenv config-add travis.php.ini

script:
  - composer ci
