sudo: false

services:
  - memcached
  - docker

language: php
php:
- 7.2

addons:
  hosts:
    - web-resource-cache-mysql-host

env:
  global:
    - APP_ENV=test
    - APP_SECRET=Secret!
    - DATABASE_URL=mysql://web_resource_cache_db_user:secret@web-resource-cache-mysql-host:33066/web_resource_cache_db_name
    - WEB_RESOURCE_CACHE_MYSQL_ROOT_PASSWORD=root
    - WEB_RESOURCE_CACHE_DATABASE_NAME=web_resource_cache_db_name
    - WEB_RESOURCE_CACHE_DATABASE_USER=web_resource_cache_db_user
    - WEB_RESOURCE_CACHE_DATABASE_PASSWORD=secret
    - WEB_RESOURCE_CACHE_DATABASE_DATA_PATH=./var/docker-mysql/web-resource-cache-db

cache:
  directories:
  - $HOME/.composer/cache/files

before_install:
  - sudo service mysql stop
  - echo $WEB_RESOURCE_CACHE_DATABASE_DATA_PATH
  - mkdir -p $WEB_RESOURCE_CACHE_DATABASE_DATA_PATH
  - docker-compose up -d
  - export DOCKER_MYSQL_IP=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.Gateway}}{{end}}' web-resource-cache-mysql`
  - echo $DOCKER_MYSQL_IP
  - echo "$DOCKER_MYSQL_IP web-resource-cache-mysql-host" | sudo tee --append /etc/hosts
  - cat /etc/hosts | grep web-resource-cache-mysql-host
  - docker-compose ps
  - docker ps -a
  - ls -la $WEB_RESOURCE_CACHE_DATABASE_DATA_PATH
  - mysql -uroot -proot --host=web-resource-cache-mysql-host --port=33066 -e "show databases;"
  - mysql -uweb_resource_cache_db_user -psecret --host=web-resource-cache-mysql-host --port=33066 -e "show databases;"
  - chmod +x ./bin/console

install:
  - composer install --ignore-platform-reqs
  - docker-compose ps
  - docker ps -a
  - php bin/console doctrine:migrations:migrate --no-interaction

before_script:
  - phpenv config-add travis.php.ini
  - ./bin/console --env=test cache:clear
  - ./bin/console --env=test cache:warmup

script:
  - composer ci

after_script:
  - docker-compose down
