sudo: false

services:
  - redis-server
  - memcached

language: php
php:
- 7.2

env:
  global:
    - APP_ENV=test
    - APP_SECRET=Secret!
    - DATABASE_URL=mysql://root:@127.0.0.1:3306/myapp_test

cache:
  directories:
  - $HOME/.composer/cache/files

before_install:
  - rm phpunit.xml.dist
  - mv phpunit.travis-ci.xml phpunit.xml.dist
  - mysql -e 'CREATE DATABASE myapp_test;'
  - chmod +x ./bin/console

install:
  - composer install --ignore-platform-reqs
  - php bin/console doctrine:migrations:migrate --no-interaction

before_script:
  - phpenv config-add travis.php.ini
  - ./bin/console --env=test cache:clear
  - ./bin/console --env=test cache:warmup

script:
  - composer ci
