sudo: false

services:
  - docker

language: minimal

addons:
  hosts:
    - mysql

env:
  global:
    - APP_ENV=test
    - APP_SECRET=Secret!
    - DATABASE_URL=mysql://async_http_retriever_db_user:secret@mysql:33066/async_http_retriever
    - ASYNC_HTTP_RETRIEVER_APP_ENV=test
    - ASYNC_HTTP_RETRIEVER_APP_SECRET=secret
    - ASYNC_HTTP_RETRIEVER_CALLBACK_ALLOWED_HOSTS=*
    - ASYNC_HTTP_RETRIEVER_RETRIEVER_TIMEOUT_SECONDS=30
    - ASYNC_HTTP_RETRIEVER_MYSQL_ROOT_PASSWORD=root
    - ASYNC_HTTP_RETRIEVER_DATABASE_NAME=async_http_retriever
    - ASYNC_HTTP_RETRIEVER_DATABASE_USER=async_http_retriever_db_user
    - ASYNC_HTTP_RETRIEVER_DATABASE_PASSWORD=secret
    - ASYNC_HTTP_RETRIEVER_DATABASE_DATA_PATH=./var/docker-mysql/async-http-retriever-db
    - ASYNC_HTTP_RETRIEVER_RABBITMQ_USER=rabbit
    - ASYNC_HTTP_RETRIEVER_RABBITMQ_PASS=rabbit

cache:
  directories:
  - $HOME/.composer/cache/files

before_install:
  - mkdir -p $ASYNC_HTTP_RETRIEVER_DATABASE_DATA_PATH
  - mkdir -p var/log/nginx
  - mkdir -p var/log/supervisor
  - chmod -R 0777 var/log

install:
  - cd docker && ./init.sh && cd ..

script:
  - cd docker && docker-compose exec -T app-web env TERM=xterm script -q -c "composer ci" /dev/null
