services:
  - docker

language: minimal

addons:
  hosts:
    - mysql

env:
  global:
    - ASYNC_HTTP_RETRIEVER_APP_ENV=test
    - ASYNC_HTTP_RETRIEVER_APP_SECRET=secret
    - ASYNC_HTTP_RETRIEVER_CALLBACK_ALLOWED_HOSTS=*
    - ASYNC_HTTP_RETRIEVER_RETRIEVER_TIMEOUT_SECONDS=30
    - ASYNC_HTTP_RETRIEVER_MYSQL_ROOT_PASSWORD=root
    - ASYNC_HTTP_RETRIEVER_MYSQL_EXPOSED_PORT=33066
    - ASYNC_HTTP_RETRIEVER_PHPMYADMIN_EXPOSED_PORT=8080
    - ASYNC_HTTP_RETRIEVER_DATABASE_NAME=async_http_retriever
    - ASYNC_HTTP_RETRIEVER_DATABASE_USER=async_http_retriever_db_user
    - ASYNC_HTTP_RETRIEVER_DATABASE_PASSWORD=secret
    - ASYNC_HTTP_RETRIEVER_DATABASE_DATA_PATH=./var/docker-mysql/async-http-retriever-db
    - ASYNC_HTTP_RETRIEVER_RABBITMQ_USER=rabbit
    - ASYNC_HTTP_RETRIEVER_RABBITMQ_PASS=rabbit
    - ASYNC_HTTP_RETRIEVER_RABBITMQ_MANAGEMENT_EXPOSED_PORT=15672
    - ASYNC_HTTP_RETRIEVER_EXPOSED_PORT=8001
    - ASYNC_HTTP_RETRIEVER_CONSUMER_COUNT=1
    - ASYNC_HTTP_RETRIEVER_HTTPBIN_EXPOSED_PORT=7000

cache:
  directories:
  - $HOME/.composer/cache/files

before_install:
  - mkdir -p $ASYNC_HTTP_RETRIEVER_DATABASE_DATA_PATH
  - mkdir -p var/log/nginx
  - mkdir -p var/log/supervisor
  - chmod -R 0777 var/log
  - chmod +x ./travis-ci/init.sh

install:
  - ./travis-ci/init.sh

script:
  - cd docker && docker-compose exec -T app-web env APP_ENV=test env TERM=xterm script -q -c "composer ci" /dev/null
