sudo: false

services:
  - memcached
  - docker

language: php
php:
- 7.2

addons:
  hosts:
    - web-resource-cache-mysql-host

env:
  global:
    - APP_ENV=test
    - APP_SECRET=Secret!
    - DATABASE_URL=mysql://web_resource_cache_db_user:secret@web-resource-cache-mysql-host:33066/web_resource_cache_db_name
    - WEB_RESOURCE_CACHE_MYSQL_ROOT_PASSWORD=root
    - WEB_RESOURCE_CACHE_DATABASE_NAME=web_resource_cache_db_name
    - WEB_RESOURCE_CACHE_DATABASE_USER=web_resource_cache_db_user
    - WEB_RESOURCE_CACHE_DATABASE_PASSWORD=secret
    - WEB_RESOURCE_CACHE_DATABASE_DATA_PATH=./var/docker-mysql/web-resource-cache-db
    - WEB_RESOURCE_CACHE_RABBITMQ_USER=rabbit
    - WEB_RESOURCE_CACHE_RABBITMQ_PASS=rabbit

cache:
  directories:
  - $HOME/.composer/cache/files

before_install:
  - mkdir -p $WEB_RESOURCE_CACHE_DATABASE_DATA_PATH
  - docker-compose -f docker/docker-compose.yml up -d
  - ./travis/docker-wait.sh
  - export DOCKER_MYSQL_IP=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.Gateway}}{{end}}' web-resource-cache-mysql`
  - echo "$DOCKER_MYSQL_IP web-resource-cache-mysql-host" | sudo tee --append /etc/hosts
  - chmod +x ./bin/console

install:
  - composer install --ignore-platform-reqs
  - php bin/console doctrine:migrations:migrate --no-interaction

before_script:
  - phpenv config-add travis.php.ini
  - ./bin/console --env=test cache:clear
  - ./bin/console --env=test cache:warmup

script:
  - composer ci

after_script:
  - docker-compose -f docker/docker-compose.yml down
