version: "3"

services:
  mysql:
    ports:
      - ${ASYNC_HTTP_RETRIEVER_MYSQL_EXPOSED_PORT}:3306

  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    ports:
    - ${ASYNC_HTTP_RETRIEVER_HTTPBIN_EXPOSED_PORT}:80

  nginx-integration:
    build:
      context: ./nginx-integration
      dockerfile: Dockerfile
    container_name: async-http-retriever-nginx-integration-${ID}
    volumes:
    - ..:/app
    - ../var/log/nginx-integration:/var/log/nginx:rw

  app-web:
    build:
      context: ./app-web
      dockerfile: Dockerfile
      args:
        APP_ENV: ${ASYNC_HTTP_RETRIEVER_APP_ENV}
        APP_SECRET: ${ASYNC_HTTP_RETRIEVER_APP_SECRET}
        CALLBACK_ALLOWED_HOSTS: ${ASYNC_HTTP_RETRIEVER_CALLBACK_ALLOWED_HOSTS}
        RETRIEVER_TIMEOUT_SECONDS: ${ASYNC_HTTP_RETRIEVER_RETRIEVER_TIMEOUT_SECONDS}
    container_name: async-http-retriever-app-web-${ID}
    environment:
      DATABASE_URL: mysql://${ASYNC_HTTP_RETRIEVER_DATABASE_USER}:${ASYNC_HTTP_RETRIEVER_DATABASE_PASSWORD}@mysql:3306/${ASYNC_HTTP_RETRIEVER_DATABASE_NAME}
    working_dir: /app
    links:
    - mysql:mysql
    - rabbitmq:rabbitmq
    - memcached:memcached
    - httpbin:httpbin
    volumes:
    - ..:/app
    depends_on:
    - mysql
    - rabbitmq
    - memcached
    - httpbin

  app-cli:
    build:
      context: ./app-cli
      dockerfile: Dockerfile
      args:
        APP_ENV: ${ASYNC_HTTP_RETRIEVER_APP_ENV}
        APP_SECRET: ${ASYNC_HTTP_RETRIEVER_APP_SECRET}
        CALLBACK_ALLOWED_HOSTS: ${ASYNC_HTTP_RETRIEVER_CALLBACK_ALLOWED_HOSTS}
        RETRIEVER_TIMEOUT_SECONDS: ${ASYNC_HTTP_RETRIEVER_RETRIEVER_TIMEOUT_SECONDS}
        CONSUMER_COUNT: ${ASYNC_HTTP_RETRIEVER_CONSUMER_COUNT}
    container_name: async-http-retriever-app-cli-${ID}
    environment:
      DATABASE_URL: mysql://${ASYNC_HTTP_RETRIEVER_DATABASE_USER}:${ASYNC_HTTP_RETRIEVER_DATABASE_PASSWORD}@mysql:3306/${ASYNC_HTTP_RETRIEVER_DATABASE_NAME}
      MESSENGER_TRANSPORT_DSN: amqp://${ASYNC_HTTP_RETRIEVER_RABBITMQ_USER}:${ASYNC_HTTP_RETRIEVER_RABBITMQ_PASS}@rabbitmq:5672/%2f/messages
    working_dir: /app
    links:
    - mysql:mysql
    - rabbitmq:rabbitmq
    - memcached:memcached
    - nginx-integration:nginx-integration
    volumes:
    - ..:/app
    - ../var/log/supervisor:/var/log/supervisor:rw
    - ../var/log/callback-responses:/var/log/callback-responses:rw
    depends_on:
    - app-web
    - mysql
    - rabbitmq
    - memcached