version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: async-http-retriever-mysql-${ID}
    environment:
      MYSQL_ROOT_PASSWORD: ${ASYNC_HTTP_RETRIEVER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${ASYNC_HTTP_RETRIEVER_DATABASE_NAME}
      MYSQL_USER: ${ASYNC_HTTP_RETRIEVER_DATABASE_USER}
      MYSQL_PASSWORD: ${ASYNC_HTTP_RETRIEVER_DATABASE_PASSWORD}
    volumes:
      - ${ASYNC_HTTP_RETRIEVER_DATABASE_DATA_PATH}:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: async-http-retriever-rabbitmq-${ID}
    environment:
      RABBITMQ_DEFAULT_USER: ${ASYNC_HTTP_RETRIEVER_RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${ASYNC_HTTP_RETRIEVER_RABBITMQ_PASS}
    ports:
      - ${ASYNC_HTTP_RETRIEVER_RABBITMQ_MANAGEMENT_EXPOSED_PORT}:15672

  nginx-app:
    build:
      context: ./nginx-app
      dockerfile: Dockerfile
      args:
        APP_SECRET: ${ASYNC_HTTP_RETRIEVER_APP_SECRET}
        DB_USER: ${ASYNC_HTTP_RETRIEVER_DATABASE_USER}
        DB_PASSWORD: ${ASYNC_HTTP_RETRIEVER_DATABASE_PASSWORD}
        DB_NAME: ${ASYNC_HTTP_RETRIEVER_DATABASE_NAME}
        RABBITMQ_USER: ${ASYNC_HTTP_RETRIEVER_RABBITMQ_USER}
        RABBITMQ_PASSWORD: ${ASYNC_HTTP_RETRIEVER_RABBITMQ_PASS}
    container_name: async-http-retriever-nginx-app-${ID}
    ports:
      - ${ASYNC_HTTP_RETRIEVER_EXPOSED_PORT}:80
    links:
      - app-web:app-web
    volumes:
      - ./nginx-app/site.tmpl:/etc/nginx-app/conf.d/site.tmpl
      - ..:/app
      - ../var/log/nginx-app:/var/log/nginx:rw

  memcached:
    image: memcached:1.5
    container_name: async-http-retriever-memcached-${ID}

  app-web:
    build:
      context: ./app-web
      dockerfile: Dockerfile
      args:
        APP_ENV: ${ASYNC_HTTP_RETRIEVER_APP_ENV}
        APP_SECRET: ${ASYNC_HTTP_RETRIEVER_APP_SECRET}
        CALLBACK_ALLOWED_HOSTS: ${ASYNC_HTTP_RETRIEVER_CALLBACK_ALLOWED_HOSTS}
        RETRIEVER_TIMEOUT_SECONDS: ${ASYNC_HTTP_RETRIEVER_RETRIEVER_TIMEOUT_SECONDS}
    container_name: async-http-retriever-app-web-${ID}
    environment:
      DATABASE_URL: mysql://${ASYNC_HTTP_RETRIEVER_DATABASE_USER}:${ASYNC_HTTP_RETRIEVER_DATABASE_PASSWORD}@mysql:3306/${ASYNC_HTTP_RETRIEVER_DATABASE_NAME}
    working_dir: /app
    links:
      - mysql:mysql
      - rabbitmq:rabbitmq
      - memcached:memcached
    volumes:
      - ..:/app
    depends_on:
      - mysql
      - rabbitmq
      - memcached

  app-cli:
    build:
      context: ./app-cli
      dockerfile: Dockerfile
      args:
        APP_ENV: ${ASYNC_HTTP_RETRIEVER_APP_ENV}
        APP_SECRET: ${ASYNC_HTTP_RETRIEVER_APP_SECRET}
        CALLBACK_ALLOWED_HOSTS: ${ASYNC_HTTP_RETRIEVER_CALLBACK_ALLOWED_HOSTS}
        RETRIEVER_TIMEOUT_SECONDS: ${ASYNC_HTTP_RETRIEVER_RETRIEVER_TIMEOUT_SECONDS}
        CONSUMER_COUNT: ${ASYNC_HTTP_RETRIEVER_CONSUMER_COUNT}
    container_name: async-http-retriever-app-cli-${ID}
    environment:
      DATABASE_URL: mysql://${ASYNC_HTTP_RETRIEVER_DATABASE_USER}:${ASYNC_HTTP_RETRIEVER_DATABASE_PASSWORD}@mysql:3306/${ASYNC_HTTP_RETRIEVER_DATABASE_NAME}
      MESSENGER_TRANSPORT_DSN: amqp://${ASYNC_HTTP_RETRIEVER_RABBITMQ_USER}:${ASYNC_HTTP_RETRIEVER_RABBITMQ_PASS}@rabbitmq:5672/%2f/messages
    working_dir: /app
    links:
      - mysql:mysql
      - rabbitmq:rabbitmq
      - memcached:memcached
    volumes:
      - ..:/app
      - ../var/log/supervisor:/var/log/supervisor:rw
      - ../var/log/callback-responses:/var/log/callback-responses:rw
    depends_on:
      - app-web
      - mysql
      - rabbitmq
      - memcached
