version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: web-resource-cache-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${WEB_RESOURCE_CACHE_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WEB_RESOURCE_CACHE_DATABASE_NAME}
      MYSQL_USER: ${WEB_RESOURCE_CACHE_DATABASE_USER}
      MYSQL_PASSWORD: ${WEB_RESOURCE_CACHE_DATABASE_PASSWORD}
    volumes:
      - ${WEB_RESOURCE_CACHE_DATABASE_DATA_PATH}:/var/lib/mysql
    ports:
      - 33066:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: web-resource-cache-phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: ${WEB_RESOURCE_CACHE_MYSQL_ROOT_PASSWORD}
      PMA_HOST: mysql
      PMA_PORT: 3306
    links:
      - mysql:mysql
    ports:
      - 8080:80
    depends_on:
      - mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: web-resource-cache-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${WEB_RESOURCE_CACHE_RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${WEB_RESOURCE_CACHE_RABBITMQ_PASS}
    ports:
      - 15672:15672
      - 5672:5672

  nginx:
    image: nginx:1.14
    container_name: web-resource-cache-nginx
    ports:
      - 8001:80
    links:
      - app-web:app-web
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ..:/app
      - ../var/log/nginx:/var/log/nginx:rw

  app-web:
    image: php:7.2-fpm
    container_name: web-resource-cache-app-web
    working_dir: /app
    links:
      - mysql:mysql
    volumes:
      - ..:/app
