version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: web-resource-cache-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${WEB_RESOURCE_CACHE_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WEB_RESOURCE_CACHE_DATABASE_NAME}
      MYSQL_USER: ${WEB_RESOURCE_CACHE_DATABASE_USER}
      MYSQL_PASSWORD: ${WEB_RESOURCE_CACHE_DATABASE_PASSWORD}
    volumes:
      - ${WEB_RESOURCE_CACHE_DATABASE_DATA_PATH}:/var/lib/mysql
    ports:
      - 33066:3306

  phpmyadmin:
    build: phpmyadmin
    container_name: web-resource-cache-phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: ${WEB_RESOURCE_CACHE_MYSQL_ROOT_PASSWORD}
      PMA_HOST: mysql
      PMA_PORT: 3306
    links:
      - mysql:mysql
    ports:
      - 8080:80
    depends_on:
      - mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: web-resource-cache-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${WEB_RESOURCE_CACHE_RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${WEB_RESOURCE_CACHE_RABBITMQ_PASS}
    ports:
      - 15672:15672
      - 5672:5672

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        APP_SECRET: ${WEB_RESOURCE_CACHE_APP_SECRET}
        DB_USER: ${WEB_RESOURCE_CACHE_DATABASE_USER}
        DB_PASSWORD: ${WEB_RESOURCE_CACHE_DATABASE_PASSWORD}
        DB_NAME: ${WEB_RESOURCE_CACHE_DATABASE_NAME}
    container_name: web-resource-cache-nginx
    ports:
      - 8001:80
    links:
      - app-web:app-web
    volumes:
      - ./nginx/site.tmpl:/etc/nginx/conf.d/site.tmpl
      - ..:/app
      - ../var/log/nginx:/var/log/nginx:rw

  memcached:
    image: memcached:1.5

  app-web:
    build:
      context: ./app-web
      dockerfile: Dockerfile
      args:
        APP_SECRET: ${WEB_RESOURCE_CACHE_APP_SECRET}
    container_name: web-resource-cache-app-web
    environment:
      DATABASE_URL: mysql://${WEB_RESOURCE_CACHE_DATABASE_USER}:${WEB_RESOURCE_CACHE_DATABASE_PASSWORD}@mysql:3306/${WEB_RESOURCE_CACHE_DATABASE_NAME}
    working_dir: /app
    links:
      - mysql:mysql
      - rabbitmq:rabbitmq
      - memcached:memcached
    volumes:
      - ..:/app
    depends_on:
      - mysql
      - rabbitmq
      - memcached

  app-cli:
    build:
      context: ./app-cli
      dockerfile: Dockerfile
      args:
        APP_SECRET: ${WEB_RESOURCE_CACHE_APP_SECRET}
    container_name: web-resource-cache-app-cli
    environment:
      DATABASE_URL: mysql://${WEB_RESOURCE_CACHE_DATABASE_USER}:${WEB_RESOURCE_CACHE_DATABASE_PASSWORD}@mysql:3306/${WEB_RESOURCE_CACHE_DATABASE_NAME}
      MESSENGER_TRANSPORT_DSN: amqp://${WEB_RESOURCE_CACHE_RABBITMQ_USER}:${WEB_RESOURCE_CACHE_RABBITMQ_PASS}@rabbitmq:5672/%2f/messages
    working_dir: /app
    links:
      - mysql:mysql
      - rabbitmq:rabbitmq
      - memcached:memcached
    volumes:
      - ..:/app
      - ../var/log/supervisor:/var/log/supervisor:rw
    depends_on:
      - app-web
      - mysql
      - rabbitmq
      - memcached
