services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  App\Tests\Services\HttpMockHandler:

  App\Tests\Services\Asserter\HttpRequestAsserter:

  async_http_retriever.http.handler_stack.retriever:
    class: GuzzleHttp\HandlerStack
    factory: 'App\Services\Http\HandlerStackFactory:create'
    arguments:
      $middlewareCollection: '@App\Services\Http\RetrieverMiddlewareCollection'
      $handler: '@App\Tests\Services\HttpMockHandler'

  async_http_retriever.http.handler_stack.sender:
    class: GuzzleHttp\HandlerStack
    factory: 'App\Services\Http\HandlerStackFactory:create'
    arguments:
      $middlewareCollection: '@App\Services\Http\SenderMiddlewareCollection'
      $handler: '@App\Tests\Services\HttpMockHandler'

  App\Services\RetryDecider:
    arguments:
    - '%retryable_statuses%'

  async_http_retriever.http.client.sender:
    public: true
    class: GuzzleHttp\Client
    factory: 'App\Services\Http\ClientFactory:create'
    arguments:
      $curlOptions: '%curl_options%'
      $handlerStack: '@async_http_retriever.http.handler_stack.sender'

  App\Services\ResponseSender:
    arguments:
      $httpClient: '@async_http_retriever.http.client.sender'
