services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  App\Tests\Services\HttpMockHandler:

  App\Tests\Services\Asserter\HttpRequestAsserter:

  web_resource_cache.http.handler_stack.retriever:
    class: GuzzleHttp\HandlerStack
    factory: 'App\Services\Http\HandlerStackFactory:create'
    arguments:
      $middlewareCollection: '@App\Services\Http\RetrieverMiddlewareCollection'
      $handler: '@App\Tests\Services\HttpMockHandler'

  web_resource_cache.http.handler_stack.sender:
    class: GuzzleHttp\HandlerStack
    factory: 'App\Services\Http\HandlerStackFactory:create'
    arguments:
      $middlewareCollection: '@App\Services\Http\SenderMiddlewareCollection'
      $handler: '@App\Tests\Services\HttpMockHandler'

  App\Services\RetryDecider:
    arguments:
    - '%retryable_statuses%'

  App\Services\CachedResourceManager:

  web_resource_cache.http.client.retriever:
    public: true
    class: GuzzleHttp\Client
    factory: 'App\Services\Http\ClientFactory:create'
    arguments:
      $curlOptions: '%curl_options%'
      $handlerStack: '@web_resource_cache.http.handler_stack.retriever'
      $config:
        cookies: '@GuzzleHttp\Cookie\CookieJarInterface'

  web_resource_cache.http.client.sender:
    public: true
    class: GuzzleHttp\Client
    factory: 'App\Services\Http\ClientFactory:create'
    arguments:
      $curlOptions: '%curl_options%'
      $handlerStack: '@web_resource_cache.http.handler_stack.sender'

  App\Services\ResponseSender:
    arguments:
      $httpClient: '@web_resource_cache.http.client.sender'
