services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  App\Tests\Services\HttpMockHandler:

  App\Services\Http\HttpHandlerStackFactory:
    arguments:
    - '@webignition\HttpHistoryContainer\Container'
    - '@App\Services\Http\HttpRetryMiddlewareFactory'
    - '@Kevinrob\GuzzleCache\CacheMiddleware'
    - '@App\Tests\Services\HttpMockHandler'

  App\Services\ResourceRetriever:

  App\Services\RetryDecider:
    arguments:
    - '%retryable_statuses%'

  App\Services\CachedResourceManager:

  web_resource_cache.http_client.retriever:
    class: GuzzleHttp\Client
    factory: 'App\Services\Http\RetrieverHttpClientFactory:create'
