services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  App\Tests\Services\HttpMockHandler:

  web_resource_cache.http.handler_stack.retriever:
    class: GuzzleHttp\HandlerStack
    factory: 'App\Services\Http\HttpHandlerStackFactory:create'
    arguments:
      $middlewareCollection: '@App\Services\Http\RetrieverHttpHandlerStackMiddlewareCollection'
      $handler: '@App\Tests\Services\HttpMockHandler'

  App\Services\RetryDecider:
    arguments:
    - '%retryable_statuses%'

  App\Services\CachedResourceManager:

  web_resource_cache.http.client.retriever:
    class: GuzzleHttp\Client
    factory: 'App\Services\Http\RetrieverHttpClientFactory:create'

  App\Services\Http\HttpClientFactory:
    arguments:
      $curlOptions: '%curl_options%'
      $handlerStack: '@web_resource_cache.http.handler_stack.sender'

  web_resource_cache.http.client.sender:
    class: GuzzleHttp\Client
    factory: 'App\Services\Http\HttpClientFactory:create'
