imports:
    - { resource: parameters/*.yaml }
    - { resource: parameters/cache-control-min-fresh/*.yaml }

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    app.callbackurl.whitelist:
        class: App\Services\Whitelist
        factory: 'App\Services\WhitelistFactory:create'
        arguments:
            $patternsString: '%env(CALLBACK_WHITELIST)%'

    App\Controller\RequestController:
        class: App\Controller\RequestController
        tags: ['controller.service_arguments']
        arguments:
            $callbackUrlWhitelist: '@app.callbackurl.whitelist'

    webignition\HttpHistoryContainer\Container:

    Kevinrob\GuzzleCache\CacheMiddleware:
        factory: 'App\Services\Http\CacheMiddlewareFactory:create'

    web_resource_cache.http.handler_stack.retriever:
        class: GuzzleHttp\HandlerStack
        factory: 'App\Services\Http\HandlerStackFactory:create'
        arguments:
            $middlewareCollection: '@App\Services\Http\RetrieverMiddlewareCollection'

    web_resource_cache.http.handler_stack.sender:
        class: GuzzleHttp\HandlerStack
        factory: 'App\Services\Http\HandlerStackFactory:create'

    GuzzleHttp\Cookie\CookieJarInterface:
        class: GuzzleHttp\Cookie\CookieJar

    App\Services\Http\RetrieverClientFactory:
        arguments:
            $curlOptions: '%curl_options%'
            $handlerStack: '@web_resource_cache.http.handler_stack.retriever'

    App\Services\Http\ClientFactory:
        arguments:
            $curlOptions: '%curl_options%'
            $handlerStack: '@web_resource_cache.http.handler_stack.sender'

    web_resource_cache.http.client.retriever:
        public: true
        class: GuzzleHttp\Client
        factory: 'App\Services\Http\RetrieverClientFactory:create'
        arguments:
            $curlOptions: '%curl_options%'

    web_resource_cache.http.client.sender:
        public: true
        class: GuzzleHttp\Client
        factory: 'App\Services\Http\ClientFactory:create'
        arguments:
            $curlOptions: '%curl_options%'

    Memcached:
        class: \Memcached
        calls:
            - [addServer, ['%memcached_host%', '%memcached_port%']]

    Doctrine\Common\Cache\MemcachedCache:
        calls:
            - [setMemcached, ['@Memcached']]

    App\Services\CachedResourceValidator:
        arguments:
            - '%cache-control-min-fresh%'

    App\Services\RetryDecider:
        arguments:
            - '%retryable_statuses%'

    App\Services\ResourceRetriever:
        arguments:
            $httpClient: '@web_resource_cache.http.client.retriever'

    # public commands required for retrieval from resque container
    App\Command\RetrieveResourceCommand:
        public: true
        arguments:
            $maxRetries: '%max_retries%'

    App\Command\SendResponseCommand:
        public: true
